# NonFungible Python API Tutorial

This tutorial aims to be a quick guide to get you started using the NonFungible API integrated into messari's python library.

In [1]:
from messari.nfts import NonFungible
nf = NonFungible()

In [2]:
collections = ['cryptopunks', 'doodles']
import pandas as pd

## API Structure
The NonFungible Python client contains a number of functions that wrap some of NonFungible's API endpoints. These include:

Functions
* get_collection_history
* get_collection_stats
* get_collection_summary

Below are a few examples to showcase the functionality and types of data each function generates.

## Functions

### get_collection_history

get collection history,

In [5]:
collection_history_df = nf.get_collection_history(collections_in=collections, length=3)
collection_history_df

  cryptopunks                                                                 \
   blockchain                                    transactionHash blockNumber
0    ethereum  0xaa40b85f4a1a16fe3f6f424ada1a99053335420b167b...    13912264
1    ethereum  0xbfe47e67ab24622b809b80fa357a2e72a8e345543b6b...    13901896
2    ethereum  0x3f2066f45f5a48e95a9a87db3f1db1789553cbece2dd...    13903771

                                                  \
             blockTimestamp assetId      project
0  2021-12-31T09:11:16.000Z    5902  cryptopunks
1  2021-12-29T18:32:33.000Z    6275  cryptopunks
2  2021-12-30T01:29:09.000Z    7622  cryptopunks

                                                         \
                                   nftAddress nftTicker
0  0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb         Ͼ
1  0xb7f7f6c52f2e2fdb1963eab30438024864c313f6    WPUNKS
2  0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb         Ͼ

                                                            ...  \
                                marketAddress     usdPrice  ...
0  0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb  1204673.400  ...
1  0x4748495153fb86637e4fdd8e50e3c1f611f15930  1133475.000  ...
2  0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb   913227.318  ...

                 doodles                                                      \
              totalPrice totalDecimalPrice feeUSDPrice         feeTotalPrice
0  200000000000000000000               200  57190.5000  15000000000000000000
1  150000000000000000000               150  42918.4125  11250000000000000000
2  120000000000000000000               120  34460.4600   9000000000000000000

                                                                      \
  feeTotalDecimalPrice                                 feeCollectors
0                15.00  [0x5b3256965e7c3cf26e11fcaf296dfc8807c01073]
1                11.25  [0x5b3256965e7c3cf26e11fcaf296dfc8807c01073]
2                 9.00  [0x5b3256965e7c3cf26e11fcaf296dfc8807c01073]

                                                          \
    saleType                                       buyer
0  secondary  0xb3b1d2405f16afc27a83fb9a43e1da5102a363d4
1  secondary  0x6ec30fd91a504aad948839b985c7263888b2ad68
2  secondary  0x4b4c13434aac5e99645a4d9e59fe497b3318f50f

                                               \
                                       seller
0  0xeef9a8b628e22ade70b509c45f6f1db1d43c0dd4
1  0x0d41f957181e584db82d2e316837b2de1738c477
2  0xd7510a925475cb8377bc8d2a7f1c792022b68df8


                                                meta
0  {'name': 'Doodle #7751', 'artist': ['Burnt Toa...
1  {'name': 'Doodle #3954', 'artist': ['Burnt Toa...
2  {'name': 'Doodle #6343', 'artist': ['Burnt Toa...

[3 rows x 44 columns]

can do '' to get all collections

In [7]:
collection_history_df = nf.get_collection_history(collections_in='')
collection_history_df.head()

                                                                             \
  blockchain                                    transactionHash blockNumber
0   ethereum  0x21dcce949d7137778294d3b40797b3f0c81928bd8661...    13928090
1   ethereum  0x851d5ec47f2d766278193961c3fd582011af1fda286f...    13896377
2   ethereum  0xaa40b85f4a1a16fe3f6f424ada1a99053335420b167b...    13912264
3   ethereum  0xbfe47e67ab24622b809b80fa357a2e72a8e345543b6b...    13901896
4   ethereum  0x44047731eb4993621a7fd0c3b55b46ebb7660fcf2900...    13935026

                                                   \
             blockTimestamp assetId       project
0  2022-01-02T20:05:08.000Z      11     superrare
1  2021-12-28T22:17:44.000Z    3562  boredapeclub
2  2021-12-31T09:11:16.000Z    5902   cryptopunks
3  2021-12-29T18:32:33.000Z    6275   cryptopunks
4  2022-01-03T21:51:13.000Z    7009     superrare

                                                         \
                                   nftAddress nftTicker
0  0x41a322b28d0ff354040e2cbc676f0320d8c8850d      SUPR
1  0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d      BAYC
2  0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb         Ͼ
3  0xb7f7f6c52f2e2fdb1963eab30438024864c313f6    WPUNKS
4  0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0      SUPR

                                                             ...  \
                                marketAddress      usdPrice  ...
0  0x41a322b28d0ff354040e2cbc676f0320d8c8850d  6.196021e+06  ...
1  0x24550d7fbe64bfdbce7704251d3fe40b8a136c91  1.636232e+06  ...
2  0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb  1.204673e+06  ...
3  0x4748495153fb86637e4fdd8e50e3c1f611f15930  1.133475e+06  ...
4  0x8c9f364bf7a56ed058fc63ef81c6cf09c833e656  9.397873e+05  ...

                                                            \
               totalPrice totalDecimalPrice    feeUSDPrice
0  1630000000000000000000         1630.0000  805482.756000
1   430000000000000000000          430.0000   81811.585000
2   315000000000000000000          315.0000            NaN
3   300000000000000000000          300.0000            NaN
4   249970700000000000000          249.9707  118613.936623

                                               \
           feeTotalPrice feeTotalDecimalPrice
0  211900000000000000000             211.9000
1   21500000000000000000              21.5000
2                   None                  NaN
3                   None                  NaN
4   31549700000000000000              31.5497

                                                                 \
                                       feeCollectors   saleType
0  [0x39cc9c86e67baf2129b80fe3414c397492ea8026, 0...  secondary
1       [0x5b3256965e7c3cf26e11fcaf296dfc8807c01073]  secondary
2                                               None  secondary
3                                               None    primary
4  [0x39cc9c86e67baf2129b80fe3414c397492ea8026, 0...  secondary

                                               \
                                        buyer
0  0x63fed38f5d6f6fd6a899451c72322c44b9c5acb0
1  0x020ca66c30bec2c4fe3861a94e4db4a498a35872
2  0x801b68cc9f4fb094a28b30ca25664051e50ad3a9
3  0xd66fe503aebe0a9ca0d0b208453a3d7106b063f2
4  0xc46db2d89327d4c41eb81c43ed5e3dff111f9a8f

                                               \
                                       seller
0  0xb67994792c214039c8328bb3e0835b6a8ea7e373
1  0xfbe5c1ab13e206688775f117a9a90153d7fdcfd2
2  0x1e3685ee600983bac782b182f245efd3bbb26455
3  0x0980d5970901349d531c9fd032dfa3132b5bec48
4  0x762da606029d3120735aa1eec15464e265db7a3c


                                                meta
0  {'artist': ['N/A'], 'name': 'All Time High in ...
1  {'name': 'Bored Ape #3562', 'eyes': 'Zombie', ...
2  {'tags': ['Hoodie', 'Small Shades', 'Shadow Be...
3                                                NaN
4  {'artist': ['XCOPY'], 'name': 'Blood Run', 'de...

[5 rows x 22 columns]

### get_collection_stats

get stats abt collection

In [3]:
collection_stats_df = nf.get_collection_stats(collections_in=collections)
collection_stats_df

,cryptopunks,doodles
count-sale-latest,104,1044
count-sale-daily,"[[1641340800, 104], [1641254400, 101], [164116...","[[1641340800, 1044], [1641254400, 1219], [1641..."
count-salesprimary-latest,10,0
count-salesprimary-daily,"[[1641340800, 10], [1641254400, 9], [164116800...","[[1641340800, 0], [1641254400, 0], [1641168000..."
count-salessecondary-latest,94,1044
count-salessecondary-daily,"[[1641340800, 94], [1641254400, 92], [16411680...","[[1641340800, 1044], [1641254400, 1219], [1641..."
sum-usd-latest,31492624.601002,29659723.218038
sum-usd-daily,"[[1641340800, 31492624.601001974], [1641254400...","[[1641340800, 29659723.21803783], [1641254400,..."
avg-usd-latest,302813.698087,28409.696569
avg-usd-daily,"[[1641340800, 302813.69808655744], [1641254400...","[[1641340800, 28409.696569001753], [1641254400..."
sum-usdprimary-latest,2709545.829378,0
sum-usdprimary-daily,"[[1641340800, 2709545.829377778], [1641254400,...","[[1641340800, 0], [1641254400, 0], [1641168000..."
sum-usdsecondary-latest,28783078.771624,29659723.218038
sum-usdsecondary-daily,"[[1641340800, 28783078.771624196], [1641254400...","[[1641340800, 29659723.21803783], [1641254400,..."
sum-feeusd-latest,242811.223109,2197695.073755
sum-feeusd-daily,"[[1641340800, 242811.22310870537], [1641254400...","[[1641340800, 2197695.073754969], [1641254400,..."
unique-wallets-latest,132,1362
unique-wallets-daily,"[[1641340800, 132], [1641254400, 127], [164116...","[[1641340800, 1362], [1641254400, 1550], [1641..."
unique-buyer-latest,69,746
unique-buyer-daily,"[[1641340800, 69], [1641254400, 67], [16411680...","[[1641340800, 746], [1641254400, 859], [164116..."
unique-seller-latest,76,805
unique-seller-daily,"[[1641340800, 76], [1641254400, 72], [16411680...","[[1641340800, 805], [1641254400, 911], [164116..."

### get_collection_summary

Retrieve quick collection summary

In [10]:
collection_summary_df = nf.get_collection_summary(collections_in=collections)
collection_summary_df

                                                  cryptopunks
name                                              cryptopunks
totals      {'alltime': {'count': 19939, 'traders': 5663, ...
tickers                          [{'project': 'cryptopunks'}]
categories                                      [Collectible]
website                 https://www.larvalabs.com/cryptopunks